[package]
name = "wavebrush"
version = "0.1.0"
authors = ["Miles Steele <miles@milessteele.com>"]
edition = "2018"

[dependencies]
stft = { git = "https://github.com/mlsteele/stft", rev = "f2bc4ba" }
hound = "3.4.0"
image = "0.21.0"
rustfft = "3.0.0"
num = "0.2.0"